# Generated by Django 3.1.12 on 2025-02-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
